export enum Cases {
  UPDATE_SESSION = 'UPDATE_SESSION',
  UPDATE_ONE_CHAT = 'UPDATE_ONE_CHAT',
  UPDATE_MULTI_CHAT = 'UPDATE_MULTI_CHAT',
  CLEAR_SESSION = 'CLEAR_SESSION',
  CLEAR_STATE = 'CLEAR_STATE',
}
